export default{
  "スタート":{
  type:'text',
  text:'技術書店の締め切りまであと7日, だけど進捗は10% あなたはどうする？',
  quickReply:{
    items:[
      {
        type:"actin",
        action:{
          type:'message',
          label:'限界まで頑張る',
          text:'[1]限界まで頑張る'
        }
      },
      {
        type:"actin",
        action:{
          type:'message',
          label:'寝る',
          text:'[2]寝る'
        }
      },
      {
        type:"actin",
        action:{
          type:'message',
          label:'出店をやめる',
          text:'[3]出店をやめる'
        }
      },
      ]
    }
  },
  "1":{
    type:'text',
    text:'頑張りすぎず寝るべし'
  },
  "2":{
    type:'text',
    text:'明日頑張ろう!'
  },
  "3":{
    type:'text',
    text:'スマブラ友達募集中',
    quickReply:{
      items:[
        {
          type:"actin",
          action:{
            type:'message',
            label:'いいよ',
            text:'[4]いいよ'
          }
        },
        {
          type:"actin",
          action:{
            type:'message',
            label:'いやよ',
            text:'[5]いやよ'
          }
        }
      ]
    },
  },
  "4":{
    type:'text',
    text:'@motto2までご連絡ください'
  }
}
